tournaments:
  create:
    name: create
    description: To register/create a tournament.
    options:
      name:
        type: str
        required: true
      description:
        type: str
        required: false
      format:
        type: str
        required: true
      date:
        type: str
        required: true
      size:
        type: int      
        required: true
      tier:
        type: int
        required: true
      game:
        type: str
        required: true
  delete:
    name: delete
    description: To delete a tournament.
    options:
      id:
        required: true
  update:
    name: update
    description: To update a tournament.
  show_bracket:
    name: show_bracket
    description: Displays a tournament's bracket.
